// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CityDayInputMap: typeof import('./src/components/CityDayInputMap.vue')['default']
    DailyIncreace: typeof import('./src/components/DailyIncreace.vue')['default']
    Home: typeof import('./src/pages/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
